# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 13 Jul 2016 16:56:16 +0000
*               @ALL          0
*               @user         8
