<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 15 Jul 2016 16:05:48 +0200
 */

$conf['title'] = 'Protocols';
$conf['template'] = 'bootstrap3';
$conf['license'] = '0';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'root';
$conf['proxy']['pass'] = '<b>Z2x1dGFtYXRl';

// end auto-generated content
